### ISSUE TITLE
Specifying data types for properties

### ISSUE THREAD

**Issue by dhodapkarsoham** [mattcasters/laura#3]
I noticed that all properties are by default loaded as strings.
Would it be possible to specify the data type of the property?
Probably in the data file itself.
Something like TotalCost(float), Name(string), Purchaseid(integer) and so on.
Is this something on the roadmap?

**Comment by mattcasters** [comment]
This is not the case at all.  Data types are detected and stored in json files next to the data files.
Since the "LOAD CSV" guessing game is unprofessional to begin with you can indeed change the data types. 
The option "ONLY_LAYOUT" allows you to do only a scan of the file to determine the file layout.  That way you can change the layouts of the files to your liking.

**Comment by dhodapkarsoham** [comment]
Nice! I definitely missed the point of layout files. Thanks for clarifying.
